# The GitHub Actions docs (https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on)
# describe other options for 'on', 'pull_request' is a good default.
name: Terraform Infracost

on: 
  workflow_call:
    inputs:
      working-directory:
        description: "Working directory"
        type: string
        required: false
        default: "."

jobs:
  infracost:
    runs-on: ubuntu-latest # The following are JavaScript actions (not Docker)
    env:
      working-directory: '.'
    name: Run Infracost
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get remove terraform
          sudo apt-get install terraform=1.0.9
          /usr/bin/terraform --version

      # IMPORTANT: add any required steps here to setup cloud credentials so Terraform can run

      - name: Terraform init
        run: terraform init
        working-directory: ${{ inputs.working-directory }}/.config/infracost

      - name: Terraform plan
        run: terraform plan -out tfplan.binary
        working-directory: ${{ inputs.working-directory }}/.config/infracost

      - name: Terraform show
        run: terraform show -json tfplan.binary > plan.json
        working-directory: ${{ inputs.working-directory }}

      # Install the Infracost CLI, see https://github.com/infracost/actions/tree/master/setup
      # for other inputs such as version, and pricing-api-endpoint (for self-hosted users).
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          # api-key: ${{ secrets.INFRACOST_API_KEY }}
          api-key: igdHpDEakW5BHaHuZ3UWwUEiprWkoVx6

      # Generate Infracost JSON output, the following docs might be useful:
      # Multi-project/workspaces: https://www.infracost.io/docs/features/config_file
      # Combine Infracost JSON files: https://www.infracost.io/docs/features/cli_commands/#combined-output-formats
      - name: Generate Infracost JSON
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ inputs.working-directory }}
        # Env vars can be set using the usual GitHub Actions syntax
        # See the list of supported Infracost env vars here: https://www.infracost.io/docs/integrations/environment_variables/
        # env:
        #   MY_ENV: ${{ secrets.MY_ENV }}

      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - name: Post Infracost comment
        run: |
          # Posts a comment to the PR using the 'update' behavior.
          # This creates a single comment and updates it. The "quietest" option.
          # The other valid behaviors are:
          #   delete-and-new - Delete previous comments and create a new one.
          #   hide-and-new - Minimize previous comments and create a new one.
          #   new - Create a new cost estimate comment on every push.
          infracost comment github --path /tmp/infracost.json \
                                   --repo $GITHUB_REPOSITORY \
                                   --github-token ${{github.token}} \
                                   --pull-request ${{github.event.pull_request.number}} \
                                   --behavior update
